# Server Config
server.port=${PORT:8081}

# Force Servlet (MVC) mode even though WebFlux is also on the classpath (used only for WebClient)
spring.main.web-application-type=servlet



# File Upload Config
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# JWT Config (Secret should be at least 256 bits/32 characters)
app.jwt.secret=${APP_JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2}
app.jwt.expiration-ms=86400000

# File Upload Directory
file.upload-dir=uploads/resumes/

# Gemini API Config
app.gemini.api-key=${GEMINI_API_KEY:YOUR_GEMINI_API_KEY_HERE}

# Spring Mail (SMTP) Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=narayanaepenagandla@gmail.com
spring.mail.password=elzr nxfd eohq iudd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

